name: BiomeReplacer
main: org.challenger2.BiomeReplacer.BiomeReplacer
version: 1.1
depend: [ProtocolLib]
permissions:
  BiomeReplacer.enable:
    description: Gives access to /BiomeReplace enable/disable
commands:
  BiomeReplacer:
    description: biomeReplacer commands
    usage: /<command> help
