name: BiomeReplacer
main: org.challenger2.BiomeReplacer.BiomeReplacer
version: ${project.version}
description: ${project.description}
website: ${project.url}
depend: [ProtocolLib]
permissions:
  BiomeReplacer.enable:
    description: Gives access to /BiomeReplace enable/disable
  BiomeReplacer.reload:
    description: Give access to /BiomeReplacer reload

commands:
  BiomeReplacer:
    description: biomeReplacer commands
    usage: /<command> help
